import React, { useState, useEffect } from 'react';
import { Project, GeneratedResult } from '../types';
import * as Icons from 'lucide-react';
import { supabase } from '../lib/supabase';
import { AGENTS } from '../constants';

interface ProjectViewProps {
  onChain: (content: string) => void;
  userId: string;
}

const ProjectView: React.FC<ProjectViewProps> = ({ onChain, userId }) => {
  const [projects, setProjects] = useState<Project[]>([]);
  const [activeProject, setActiveProject] = useState<Project | null>(null);
  const [results, setResults] = useState<GeneratedResult[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [newProjectName, setNewProjectName] = useState('');

  // Fetch Projects
  useEffect(() => {
    fetchProjects();
  }, [userId]);

  // Fetch Results when active project changes
  useEffect(() => {
    if (activeProject) {
      fetchResults(activeProject.id);
    } else {
      setResults([]);
    }
  }, [activeProject]);

  const fetchProjects = async () => {
    setLoading(true);
    
    // Mock for Demo User
    if (userId === 'demo-user') {
        const demoProject = { id: 'demo-p1', name: 'Demo Project', created_at: new Date().toISOString(), user_id: 'demo-user' };
        setProjects([demoProject]);
        setActiveProject(demoProject);
        setResults([{
            id: 'res-1',
            project_id: 'demo-p1',
            agent_id: 'ad-copy',
            content: "This is a demo result generated by RevenuePilot.\n\n### Benefit:\nIt helps you test without needing a database connection.",
            inputs: {},
            created_at: new Date().toISOString(),
            user_id: 'demo-user'
        }]);
        setLoading(false);
        return;
    }

    const { data, error } = await supabase
      .from('projects')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });
    
    if (error) console.error('Error fetching projects:', error);
    if (data) {
      setProjects(data);
      if (data.length > 0 && !activeProject) setActiveProject(data[0]);
    }
    setLoading(false);
  };

  const fetchResults = async (projectId: string) => {
    if (userId === 'demo-user') return; // Handled in init

    const { data, error } = await supabase
      .from('generated_content')
      .select('*')
      .eq('project_id', projectId)
      .order('created_at', { ascending: false });

    if (error) console.error('Error fetching content:', error);
    if (data) setResults(data);
  };

  const createProject = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newProjectName.trim()) return;
    
    if (userId === 'demo-user') {
        const newProj = { id: `demo-${Date.now()}`, name: newProjectName, created_at: new Date().toISOString(), user_id: 'demo-user' };
        setProjects([newProj, ...projects]);
        setActiveProject(newProj);
        setNewProjectName('');
        setCreating(false);
        return;
    }

    const { data, error } = await supabase
      .from('projects')
      .insert([{ user_id: userId, name: newProjectName }])
      .select()
      .single();

    if (error) {
      alert('Error creating project');
    } else if (data) {
      setProjects([data, ...projects]);
      setActiveProject(data);
      setNewProjectName('');
      setCreating(false);
    }
  };

  const getAgentName = (id: string) => AGENTS.find(a => a.id === id)?.name || id;

  if (loading && projects.length === 0) {
    return <div className="flex justify-center items-center h-full"><Icons.Loader2 className="animate-spin text-indigo-600" size={32} /></div>;
  }

  return (
    <div className="flex h-full bg-slate-50 dark:bg-slate-950 transition-colors">
      {/* Sidebar */}
      <div className="w-72 bg-white dark:bg-slate-900 border-r border-slate-200 dark:border-slate-800 flex flex-col h-full transition-colors">
        <div className="p-4 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center">
          <h2 className="font-bold text-slate-800 dark:text-white flex items-center gap-2">
            <Icons.Folder size={20} className="text-indigo-600" /> My Projects
          </h2>
          <button 
            onClick={() => setCreating(true)}
            className="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg text-slate-500 dark:text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
          >
            <Icons.Plus size={20} />
          </button>
        </div>
        
        {creating && (
          <form onSubmit={createProject} className="p-3 bg-slate-50 dark:bg-slate-800 border-b border-slate-100 dark:border-slate-700 animate-in fade-in slide-in-from-top-2">
            <input
              autoFocus
              type="text"
              placeholder="Project Name..."
              className="w-full text-sm p-2 rounded border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white focus:ring-2 focus:ring-indigo-500 outline-none mb-2"
              value={newProjectName}
              onChange={(e) => setNewProjectName(e.target.value)}
            />
            <div className="flex justify-end gap-2">
              <button type="button" onClick={() => setCreating(false)} className="text-xs px-2 py-1 text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200">Cancel</button>
              <button type="submit" className="text-xs px-2 py-1 bg-indigo-600 text-white rounded hover:bg-indigo-700">Create</button>
            </div>
          </form>
        )}

        <div className="flex-1 overflow-y-auto p-2 space-y-1">
          {projects.map(project => (
            <button
              key={project.id}
              onClick={() => setActiveProject(project)}
              className={`w-full text-left px-4 py-3 rounded-lg text-sm font-medium transition-all flex items-center justify-between group ${
                activeProject?.id === project.id 
                  ? 'bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 border border-indigo-100 dark:border-indigo-800' 
                  : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800 border border-transparent'
              }`}
            >
              <span className="truncate">{project.name}</span>
            </button>
          ))}
          {projects.length === 0 && !creating && (
            <div className="text-center py-8 text-slate-400 text-sm">No projects. Create one!</div>
          )}
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 overflow-y-auto p-8">
        {activeProject ? (
          <div className="max-w-4xl mx-auto">
            <div className="flex justify-between items-center mb-8">
              <div>
                <h1 className="text-2xl font-bold text-slate-900 dark:text-white">{activeProject.name}</h1>
                <p className="text-slate-500 dark:text-slate-400 text-sm flex items-center gap-2">
                  <Icons.Clock size={14} /> Created {new Date(activeProject.created_at).toLocaleDateString()}
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 gap-6">
              {results.length === 0 ? (
                 <div className="text-center py-20 bg-white dark:bg-slate-900 rounded-xl border-2 border-dashed border-slate-200 dark:border-slate-800">
                   <Icons.Sparkles className="mx-auto text-slate-300 dark:text-slate-600 mb-3" size={48} />
                   <p className="text-slate-500 dark:text-slate-400">No AI generations in this project yet.</p>
                 </div>
              ) : (
                results.map((result) => (
                  <div key={result.id} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300">
                    <div className="bg-slate-50 dark:bg-slate-800/50 px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center">
                      <div className="flex items-center gap-3">
                        <div className="p-2 bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm text-indigo-600 dark:text-indigo-400">
                           <Icons.FileText size={18} />
                        </div>
                        <div>
                          <h3 className="font-semibold text-slate-800 dark:text-slate-200 text-sm">{getAgentName(result.agent_id)}</h3>
                          <p className="text-xs text-slate-500 dark:text-slate-400">{new Date(result.created_at).toLocaleString()}</p>
                        </div>
                      </div>
                      <div className="flex gap-2">
                        <button 
                          className="flex items-center gap-1 px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-medium text-slate-600 dark:text-slate-300 hover:text-indigo-600 dark:hover:text-indigo-400 hover:border-indigo-300 transition-all"
                          onClick={() => onChain(result.content)}
                        >
                          <Icons.Workflow size={14} /> Chain Agent
                        </button>
                        <button 
                          className="p-1.5 hover:bg-white dark:hover:bg-slate-800 rounded text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
                          onClick={() => navigator.clipboard.writeText(result.content)}
                        >
                          <Icons.Copy size={16} />
                        </button>
                      </div>
                    </div>
                    <div className="p-6 max-h-96 overflow-y-auto">
                      <p className="whitespace-pre-wrap text-sm text-slate-700 dark:text-slate-300 leading-relaxed font-mono">
                        {result.content}
                      </p>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        ) : (
          <div className="flex items-center justify-center h-full text-slate-400 dark:text-slate-600">Select or create a project to view content</div>
        )}
      </div>
    </div>
  );
};

export default ProjectView;